name: Code check

on:
  push:
    branches: ["stable", "preview"]
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint